import re
from datetime import datetime

def transform_str_to_int(value):
    """Rimuove tutti i caratteri non numerici da una stringa e restituisce un intero."""
    if value is not None:
        numeric_value = re.sub(r'\D', '', value)
        if numeric_value:
            return int(numeric_value)
    return None

def parse_date(date_str):
    """Converte una stringa nel formato 'YYYY-MM-DD' in un oggetto datetime.date."""
    if date_str is not None:
        return datetime.strptime(date_str, '%Y-%m-%d').date()
    return None

def translate_role(role):
    """
    Traduci il ruolo del giocatore in italiano.
    """
    role = role.lower()
    if role == "goalkeeper":
        return "Portiere"
    elif role == "defender":
        return "Difensore"
    elif role == "midfielder":
        return "Centrocampista"
    elif role == "attacker":
        return "Attaccante"
    else:
        return None


def translate_nationality(nationality):
    """
    Traduci la nazionalità del giocatore in italiano.
    """
    nationality_map = {
        "afghanistan": "Afghanistan",
        "albania": "Albania",
        "algeria": "Algeria",
        "andorra": "Andorra",
        "angola": "Angola",
        "argentina": "Argentina",
        "armenia": "Armenia",
        "australia": "Australia",
        "austria": "Austria",
        "azerbaijan": "Azerbaijan",
        "bahamas": "Bahamas",
        "bahrain": "Bahrain",
        "bangladesh": "Bangladesh",
        "barbados": "Barbados",
        "belarus": "Bielorussia",
        "belgium": "Belgio",
        "belize": "Belize",
        "benin": "Benin",
        "bhutan": "Bhutan",
        "bolivia": "Bolivia",
        "bosnia and herzegovina": "Bosnia ed Erzegovina",
        "botswana": "Botswana",
        "brazil": "Brasile",
        "brunei": "Brunei",
        "bulgaria": "Bulgaria",
        "burkina faso": "Burkina Faso",
        "burundi": "Burundi",
        "cabo verde": "Capo Verde",
        "cambodia": "Cambogia",
        "cameroon": "Camerun",
        "canada": "Canada",
        "central african republic": "Repubblica Centrafricana",
        "chad": "Ciad",
        "chile": "Cile",
        "china": "Cina",
        "colombia": "Colombia",
        "comoros": "Comore",
        "congo": "Congo",
        "congo dr": "Congo",
        "costa rica": "Costa Rica",
        "côte d'ivoire": "Costa d'Avorio",
        "croatia": "Croazia",
        "cuba": "Cuba",
        "cyprus": "Cipro",
        "czech republic": "Repubblica Ceca",
        "czechia": "Repubblica Ceca",
        "denmark": "Danimarca",
        "djibouti": "Gibuti",
        "dominica": "Dominica",
        "dominican republic": "Repubblica Dominicana",
        "ecuador": "Ecuador",
        "egypt": "Egitto",
        "el salvador": "El Salvador",
        "england": "Inghilterra",
        "equatorial guinea": "Guinea Equatoriale",
        "eritrea": "Eritrea",
        "estonia": "Estonia",
        "eswatini": "Eswatini",
        "ethiopia": "Etiopia",
        "fiji": "Figi",
        "finland": "Finlandia",
        "france": "Francia",
        "gabon": "Gabon",
        "gambia": "Gambia",
        "georgia": "Georgia",
        "germany": "Germania",
        "ghana": "Ghana",
        "greece": "Grecia",
        "grenada": "Grenada",
        "guatemala": "Guatemala",
        "guinea": "Guinea",
        "guinea-bissau": "Guinea-Bissau",
        "guyana": "Guyana",
        "haiti": "Haiti",
        "honduras": "Honduras",
        "hungary": "Ungheria",
        "iceland": "Islanda",
        "india": "India",
        "indonesia": "Indonesia",
        "iran": "Iran",
        "iraq": "Iraq",
        "ireland": "Irlanda",
        "israel": "Israele",
        "italy": "Italia",
        "jamaica": "Giamaica",
        "japan": "Giappone",
        "jordan": "Giordania",
        "kazakhstan": "Kazakistan",
        "kenya": "Kenya",
        "kiribati": "Kiribati",
        "korea republic": "Corea del Sud",
        "kuwait": "Kuwait",
        "kyrgyzstan": "Kirghizistan",
        "laos": "Laos",
        "latvia": "Lettonia",
        "lebanon": "Libano",
        "lesotho": "Lesotho",
        "liberia": "Liberia",
        "libya": "Libia",
        "liechtenstein": "Liechtenstein",
        "lithuania": "Lituania",
        "luxembourg": "Lussemburgo",
        "madagascar": "Madagascar",
        "malawi": "Malawi",
        "malaysia": "Malaysia",
        "maldives": "Maldive",
        "mali": "Mali",
        "malta": "Malta",
        "marshall islands": "Isole Marshall",
        "mauritania": "Mauritania",
        "mauritius": "Mauritius",
        "mexico": "Messico",
        "micronesia": "Micronesia",
        "moldova": "Moldavia",
        "monaco": "Monaco",
        "mongolia": "Mongolia",
        "montenegro": "Montenegro",
        "morocco": "Marocco",
        "mozambique": "Mozambico",
        "myanmar": "Myanmar",
        "namibia": "Namibia",
        "nauru": "Nauru",
        "nepal": "Nepal",
        "netherlands": "Paesi Bassi",
        "new zealand": "Nuova Zelanda",
        "nicaragua": "Nicaragua",
        "niger": "Niger",
        "nigeria": "Nigeria",
        "north korea": "Corea del Nord",
        "north macedonia": "Macedonia del Nord",
        "norway": "Norvegia",
        "oman": "Oman",
        "pakistan": "Pakistan",
        "palau": "Palau",
        "palestine": "Palestina",
        "panama": "Panama",
        "papua new guinea": "Papua Nuova Guinea",
        "paraguay": "Paraguay",
        "peru": "Perù",
        "philippines": "Filippine",
        "poland": "Polonia",
        "portugal": "Portogallo",
        "qatar": "Qatar",
        "republic of ireland": "Irlanda",
        "romania": "Romania",
        "russia": "Russia",
        "rwanda": "Ruanda",
        "saint kitts and nevis": "Saint Kitts e Nevis",
        "saint lucia": "Saint Lucia",
        "saint vincent and the grenadines": "Saint Vincent e Grenadine",
        "samoa": "Samoa",
        "san marino": "San Marino",
        "sao tome and principe": "São Tomé e Príncipe",
        "saudi arabia": "Arabia Saudita",
        "scotland": "Scotland",
        "senegal": "Senegal",
        "serbia": "Serbia",
        "seychelles": "Seychelles",
        "sierra leone": "Sierra Leone",
        "singapore": "Singapore",
        "slovakia": "Slovacchia",
        "slovenia": "Slovenia",
        "solomon islands": "Isole Salomone",
        "somalia": "Somalia",
        "south africa": "Sudafrica",
        "south korea": "Corea del Sud",
        "south sudan": "Sud Sudan",
        "spain": "Spagna",
        "sri lanka": "Sri Lanka",
        "sudan": "Sudan",
        "suriname": "Suriname",
        "sweden": "Svezia",
        "switzerland": "Svizzera",
        "syria": "Siria",
        "taiwan": "Taiwan",
        "tajikistan": "Tagikistan",
        "tanzania": "Tanzania",
        "thailand": "Thailandia",
        "timor-leste": "Timor Est",
        "togo": "Togo",
        "tonga": "Tonga",
        "trinidad and tobago": "Trinidad e Tobago",
        "tunisia": "Tunisia",
        "turkey": "Turchia",
        "türkiye": "Turchia",
        "turkmenistan": "Turkmenistan",
        "tuvalu": "Tuvalu",
        "uganda": "Uganda",
        "ukraine": "Ucraina",
        "united arab emirates": "Emirati Arabi Uniti",
        "united kingdom": "Regno Unito",
        "united states": "Stati Uniti",
        "uruguay": "Uruguay",
        "uzbekistan": "Uzbekistan",
        "vanuatu": "Vanuatu",
        "vatican city": "Città del Vaticano",
        "venezuela": "Venezuela",
        "vietnam": "Vietnam",
        "yemen": "Yemen",
        "zambia": "Zambia",
        "zimbabwe": "Zimbabwe"
    }
    return nationality_map.get(nationality.lower(), nationality)